import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import { connectDB, disconnectDB } from '../config/db.js';
import User from '../models/User.js';
import Product from '../models/Product.js';
import Category from '../models/Category.js';
import Coupon from '../models/Coupon.js';
import Review from '../models/Review.js';

dotenv.config();

const categoriesData = [
  // Men
  {
    name: 'Sherwanis',
    slug: 'sherwanis',
    gender: 'men',
    description: 'Bespoke royal groom sherwanis woven with authentic raw silk and zardozi threadwork.',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },
  {
    name: 'Tuxedos',
    slug: 'tuxedos',
    gender: 'men',
    description: 'Black-tie luxury tuxedos sculpted with Italian wool and satin peak lapels.',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },
  {
    name: 'Suits',
    slug: 'suits',
    gender: 'men',
    description: 'Tailored two-piece and three-piece sartorial suits for discerning gentlemen.',
    image: 'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=1000&q=80',
    featured: false,
  },
  {
    name: 'Kurta Sets',
    slug: 'kurta',
    gender: 'men',
    description: 'Handcrafted chanderi silk and chikankari kurtas with draped churidars.',
    image: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },
  {
    name: 'Blazers',
    slug: 'blazers',
    gender: 'men',
    description: 'Hand-tailored velvet and jacquard evening jackets with metallic embroidery.',
    image: 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=1000&q=80',
    featured: false,
  },
  {
    name: 'Men Wedding Wear',
    slug: 'wedding-wear',
    gender: 'men',
    description: 'Comprehensive Dulha collections including angrakhas, bandhgalas and safas.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },

  // Women
  {
    name: 'Bridal Lehengas',
    slug: 'bridal',
    gender: 'women',
    description: 'Regal bridal lehengas adorned with heritage dabka, moti, and resham threads.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },
  {
    name: 'Lehengas',
    slug: 'lehenga',
    gender: 'women',
    description: 'Celebratory flared lehengas crafted in organza, georgette, and pure silk.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },
  {
    name: 'Designer Sarees',
    slug: 'sarees',
    gender: 'women',
    description: 'Heirloom Kanjeevarams, Banarasi weaves, and pre-draped cocktail sarees.',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },
  {
    name: 'Gowns',
    slug: 'gowns',
    gender: 'women',
    description: 'Dramatic red-carpet and reception gowns with sweeping trails and hand-sewn crystals.',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },
  {
    name: 'Luxury Suits',
    slug: 'suits-women',
    gender: 'women',
    description: 'Sharara sets, Anarkalis, and Pakistani long silhouettes with intricate handcrafting.',
    image: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1000&q=80',
    featured: false,
  },
  {
    name: 'Women Wedding Wear',
    slug: 'women-wedding-wear',
    gender: 'women',
    description: 'Exclusive trousseau wear for Sangeet, Mehendi, and Grand Wedding celebrations.',
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1000&q=80',
    featured: true,
  },
];

const productsData = [
  // ================= MEN'S COLLECTION =================
  {
    name: 'The Royal Sovereign Ivory Wedding Sherwani',
    slug: 'royal-sovereign-ivory-sherwani',
    gender: 'men',
    category: 'Sherwanis',
    subcategory: 'Wedding Wear',
    price: 84999,
    salePrice: 76999,
    sku: 'DT-MSH-001',
    description: 'An ode to Mughal royalty, this majestic ivory sherwani is handcrafted in pure Matka silk with antique gold zardozi, French knots, and pearl bead embellishments. Finished with ornamental gem buttons and matched with an organza stole.',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL', 'Custom'],
    colors: [{ name: 'Royal Ivory', hex: '#FDFBF7' }, { name: 'Antique Gold', hex: '#D4AF37' }],
    stock: 6,
    fabric: 'Pure Matka Silk & Handloom Zardozi',
    tags: ['Dulha', 'Groom', 'Wedding', 'Royal', 'Sherwani'],
    rating: 4.9,
    reviewCount: 18,
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    name: 'Midnight Black Velvet Imperial Bandhgala',
    slug: 'midnight-black-velvet-bandhgala',
    gender: 'men',
    category: 'Suits',
    subcategory: 'Bandhgala',
    price: 49999,
    salePrice: 44999,
    sku: 'DT-MBG-002',
    description: 'Exquisitely structured Jodhpuri bandhgala crafted from plush Italian micro-velvet. Features understated tone-on-tone thread embroidery at the mandarin collar and cuffs, paired with custom lion crest horn buttons.',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Obsidian Black', hex: '#0B0B0B' }],
    stock: 8,
    fabric: 'Italian Micro-Velvet',
    tags: ['Bandhgala', 'Velvet', 'Cocktail', 'Groom'],
    rating: 4.8,
    reviewCount: 14,
    featured: true,
    trending: false,
    newArrival: true,
  },
  {
    name: 'Grand Monarch Obsidian Tuxedo',
    slug: 'grand-monarch-obsidian-tuxedo',
    gender: 'men',
    category: 'Tuxedos',
    subcategory: 'Black Tie',
    price: 62000,
    salePrice: 56000,
    sku: 'DT-MTX-003',
    description: 'The definitive black-tie statement. Constructed in super 140s Tasmanian wool with pure Duchess satin shawl lapels and besom pockets. Cut for a modern tapered silhouette that commands every gala reception.',
    images: [
      'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL', 'Custom'],
    colors: [{ name: 'Jet Black', hex: '#050505' }],
    stock: 5,
    fabric: 'Super 140s Wool & Duchess Satin',
    tags: ['Tuxedo', 'Black Tie', 'Reception', 'Cocktail'],
    rating: 5.0,
    reviewCount: 22,
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    name: 'Heritage Raw Silk Kurta Set with Bundi',
    slug: 'heritage-raw-silk-kurta-bundi-set',
    gender: 'men',
    category: 'Kurta Sets',
    subcategory: 'Festive Wear',
    price: 28999,
    salePrice: 24999,
    sku: 'DT-MKU-004',
    description: 'Chanderi silk draped kurta paired with an intricately woven jacquard bundi jacket in dull gold motifs. Ideal for Haldi, Sangeet, and intimate festive gatherings.',
    images: [
      'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Mustard Gold', hex: '#E1AD01' }, { name: 'Cream Silk', hex: '#FFFDD0' }],
    stock: 12,
    fabric: 'Pure Chanderi Silk & Banarasi Jacquard',
    tags: ['Kurta', 'Bundi', 'Haldi', 'Sangeet'],
    rating: 4.7,
    reviewCount: 9,
    featured: false,
    trending: true,
    newArrival: true,
  },
  {
    name: 'Emerald Peacock Embroidered Evening Blazer',
    slug: 'emerald-peacock-evening-blazer',
    gender: 'men',
    category: 'Blazers',
    subcategory: 'Evening Jackets',
    price: 38500,
    salePrice: null,
    sku: 'DT-MBL-005',
    description: 'Deep bottle-green velvet dinner jacket elevated with stylized metallic peacock feather embroidery down the shoulder line. Designed for standout cocktail soirées.',
    images: [
      'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Royal Emerald', hex: '#0B3B24' }],
    stock: 4,
    fabric: 'Silk Velvet & Gold Thread',
    tags: ['Blazer', 'Velvet', 'Cocktail', 'Reception'],
    rating: 4.8,
    reviewCount: 11,
    featured: false,
    trending: true,
    newArrival: true,
  },
  {
    name: 'Crimson Nawab Bridal Sherwani Set',
    slug: 'crimson-nawab-bridal-sherwani-set',
    gender: 'men',
    category: 'Sherwanis',
    subcategory: 'Wedding Wear',
    price: 98000,
    salePrice: 89000,
    sku: 'DT-MSH-006',
    description: 'An opulent crimson and maroon velvet sherwani adorned with heritage dabka and kashmiri tilla embroidery. Accompanied by a coordinated safa, kamarbandh, and mojari set.',
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Royal Crimson', hex: '#800020' }],
    stock: 3,
    fabric: 'Heritage Velvet & Dabka Resham',
    tags: ['Dulha', 'Groom', 'Bridal', 'Velvet'],
    rating: 5.0,
    reviewCount: 16,
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    name: 'Sartorial Charcoal Windowpane Three-Piece Suit',
    slug: 'sartorial-charcoal-windowpane-suit',
    gender: 'men',
    category: 'Suits',
    subcategory: 'Three Piece',
    price: 45000,
    salePrice: 39500,
    sku: 'DT-MSU-007',
    description: 'Impeccably tailored three-piece suit featuring a subtle champagne windowpane overcheck in breathable merino wool. Includes double-breasted waistcoat.',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Charcoal Grey', hex: '#36454F' }],
    stock: 9,
    fabric: '100% Australian Merino Wool',
    tags: ['Suit', 'Three Piece', 'Formal', 'Reception'],
    rating: 4.6,
    reviewCount: 8,
    featured: false,
    trending: false,
    newArrival: true,
  },
  {
    name: 'Ivory Chikankari Mukaish Silk Kurta Set',
    slug: 'ivory-chikankari-mukaish-kurta-set',
    gender: 'men',
    category: 'Kurta Sets',
    subcategory: 'Day Wedding',
    price: 32000,
    salePrice: 28500,
    sku: 'DT-MKU-008',
    description: 'Hand-embroidered Lucknowi chikankari on sheer georgette layered over pure mulmul lining, accented with real silver mukaish dots and mother-of-pearl buttons.',
    images: [
      'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL', 'Custom'],
    colors: [{ name: 'Pearl White', hex: '#FDFBF7' }],
    stock: 14,
    fabric: 'Georgette, Mulmul & Silver Mukaish',
    tags: ['Kurta', 'Chikankari', 'Day Wedding', 'Mehendi'],
    rating: 4.9,
    reviewCount: 20,
    featured: true,
    trending: false,
    newArrival: true,
  },
  {
    name: 'Midnight Sapphire Double-Breasted Tuxedo',
    slug: 'midnight-sapphire-double-breasted-tuxedo',
    gender: 'men',
    category: 'Tuxedos',
    subcategory: 'Evening Wear',
    price: 68000,
    salePrice: 59999,
    sku: 'DT-MTX-009',
    description: 'Deep sapphire blue double-breasted silhouette with black grosgrain shawl lapels. Tailored with a clean taper and structured equestrian shoulder pads.',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Sapphire Navy', hex: '#0F2537' }],
    stock: 4,
    fabric: 'Superfine Wool Mohair Blend',
    tags: ['Tuxedo', 'Sapphire', 'Cocktail', 'Gala'],
    rating: 4.9,
    reviewCount: 15,
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    name: 'Antique Gold Brocade Achkan with Dhoti',
    slug: 'antique-gold-brocade-achkan-dhoti',
    gender: 'men',
    category: 'Men Wedding Wear',
    subcategory: 'Achkan',
    price: 52000,
    salePrice: 47000,
    sku: 'DT-MWE-010',
    description: 'Varanasi pure zari brocade knee-length achkan styled with a pre-pleated silk dhoti pant. An immortal classic for authentic Indian groom heritage.',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Antique Gold', hex: '#CFB53B' }],
    stock: 5,
    fabric: 'Banarasi Zari Brocade & Dupion Silk',
    tags: ['Achkan', 'Dhoti', 'Dulha', 'Vedic'],
    rating: 4.7,
    reviewCount: 7,
    featured: false,
    trending: false,
    newArrival: true,
  },

  // ================= WOMEN'S BRIDAL & OCCASION WEAR =================
  {
    name: 'The Empress Noor Crimson Heritage Bridal Lehenga',
    slug: 'empress-noor-crimson-bridal-lehenga',
    gender: 'women',
    category: 'Bridal Lehengas',
    subcategory: 'Bridal Couture',
    price: 185000,
    salePrice: 165000,
    sku: 'DT-WBL-001',
    description: 'The pinnacle of Dulhan couture. Hand-spun silk velvet lehenga in royal crimson featuring 24 kalis densely encrusted with 24k gold resham, salma sitara, and real Basra pearl accents. Paired with dual veils: a sheer scalloped organza dupatta and a velvet head trail.',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Royal Crimson Red', hex: '#990000' }, { name: 'Sindoor Scarlet', hex: '#B22222' }],
    stock: 4,
    fabric: 'Silk Velvet, Pure Organza & Hand Zardozi',
    tags: ['Dulhan', 'Bridal', 'Lehenga', 'Red', 'Heritage'],
    rating: 5.0,
    reviewCount: 32,
    featured: true,
    trending: true,
    newArrival: false,
  },
  {
    name: 'Maharani Ivory & Champagne Zardozi Lehenga',
    slug: 'maharani-ivory-champagne-zardozi-lehenga',
    gender: 'women',
    category: 'Bridal Lehengas',
    subcategory: 'Modern Bridal',
    price: 145000,
    salePrice: 129999,
    sku: 'DT-WBL-002',
    description: 'Designed for the modern romantic bride. Pale champagne raw silk layered under sheer net with intricate rose-gold bullion thread, swarovski crystals, and micro-sequins depicting palace arches.',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Champagne Ivory', hex: '#F7E7CE' }, { name: 'Rose Gold', hex: '#B76E79' }],
    stock: 5,
    fabric: 'Raw Silk & Fine French Net',
    tags: ['Bridal', 'Ivory', 'Modern Bride', 'Zardozi'],
    rating: 4.9,
    reviewCount: 26,
    featured: true,
    trending: true,
    newArrival: true,
  },
  {
    name: 'Kanchipuram Pure Gold Zari Bridal Saree',
    slug: 'kanchipuram-pure-gold-zari-bridal-saree',
    gender: 'women',
    category: 'Designer Sarees',
    subcategory: 'Handloom Silks',
    price: 68000,
    salePrice: 59500,
    sku: 'DT-WSR-003',
    description: 'Handwoven in the temple towns of Tamil Nadu over four weeks. Woven with double-warp mulberry silk and heavy pure silver zari dipped in 24k gold. Featuring majestic mayil (peacock) and rudraksha border motifs.',
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['Custom'],
    colors: [{ name: 'Temple Vermilion', hex: '#E34234' }, { name: 'Sunset Rani Pink', hex: '#C21E56' }],
    stock: 7,
    fabric: 'Pure Mulberry Silk & Certified Silver Zari',
    tags: ['Saree', 'Kanjeevaram', 'Silk', 'Bridal', 'Handloom'],
    rating: 5.0,
    reviewCount: 19,
    featured: true,
    trending: false,
    newArrival: false,
  },
  {
    name: 'The Celeste Emerald Sculpted Crystal Reception Gown',
    slug: 'celeste-emerald-sculpted-reception-gown',
    gender: 'women',
    category: 'Gowns',
    subcategory: 'Reception Couture',
    price: 92000,
    salePrice: 84000,
    sku: 'DT-WGW-004',
    description: 'A masterpiece in dramatic red-carpet elegance. Corseted bodice encrusted with hand-placed emerald cut glass crystals and bugle beads cascading down into an architectural fluted flare with a 2-meter train.',
    images: [
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'Custom'],
    colors: [{ name: 'Deep Emerald', hex: '#043927' }],
    stock: 3,
    fabric: 'Duchess Satin & Beaded Tulle',
    tags: ['Gown', 'Reception', 'Cocktail', 'Emerald'],
    rating: 4.9,
    reviewCount: 15,
    featured: true,
    trending: true,
    newArrival: true,
  },
  {
    name: 'Midnight Rose Gold Handcrafted Cocktail Lehenga',
    slug: 'midnight-rose-gold-cocktail-lehenga',
    gender: 'women',
    category: 'Lehengas',
    subcategory: 'Cocktail & Sangeet',
    price: 78000,
    salePrice: 69999,
    sku: 'DT-WLE-005',
    description: 'Midnight navy organza base highlighted with thousands of metallic copper sequins, glass pipes, and laser-cut floral foliage. Features an off-shoulder corseted blouse.',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Midnight Navy', hex: '#001B3A' }],
    stock: 6,
    fabric: 'Sheer Organza & Metallic Bugle Sequins',
    tags: ['Lehenga', 'Sangeet', 'Cocktail', 'Reception'],
    rating: 4.8,
    reviewCount: 12,
    featured: false,
    trending: true,
    newArrival: true,
  },
  {
    name: 'Varanasi Raktambari Banarasi Brocade Saree',
    slug: 'varanasi-banarasi-brocade-saree',
    gender: 'women',
    category: 'Designer Sarees',
    subcategory: 'Banarasi',
    price: 54000,
    salePrice: 48000,
    sku: 'DT-WSR-006',
    description: 'Woven with timeless Kadhwa technique where each gold zari motif is individually engraved on scarlet katan silk. A prized collectible to pass down generations.',
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['Custom'],
    colors: [{ name: 'Deep Carmine Red', hex: '#960018' }],
    stock: 8,
    fabric: 'Pure Katan Silk & Zari',
    tags: ['Banarasi', 'Saree', 'Heritage', 'Trousseau'],
    rating: 4.9,
    reviewCount: 21,
    featured: true,
    trending: false,
    newArrival: false,
  },
  {
    name: 'Shahi Anarkali Gown with Pearl Choker Blouse',
    slug: 'shahi-anarkali-gown-pearl-blouse',
    gender: 'women',
    category: 'Luxury Suits',
    subcategory: 'Anarkali',
    price: 46000,
    salePrice: 39999,
    sku: 'DT-WSU-007',
    description: 'Floor-length flared 56-kali Anarkali in antique champagne georgette, crowned with an attached pearl choker neckline and resham-embroidered borders.',
    images: [
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL', 'Custom'],
    colors: [{ name: 'Champagne Gold', hex: '#F1E9D2' }],
    stock: 9,
    fabric: 'Pure Silk Georgette & Seed Pearls',
    tags: ['Anarkali', 'Suit', 'Wedding', 'Festive'],
    rating: 4.7,
    reviewCount: 10,
    featured: false,
    trending: true,
    newArrival: true,
  },
  {
    name: 'Plum Velvet Sharara Set with Zardozi Kurti',
    slug: 'plum-velvet-sharara-set-zardozi',
    gender: 'women',
    category: 'Luxury Suits',
    subcategory: 'Sharara Set',
    price: 52000,
    salePrice: 45000,
    sku: 'DT-WSU-008',
    description: 'Rich royal plum silk velvet short kurti with heavy marodi and pitta embroidery, accompanied by an ultra-flared double-layer crushed georgette sharara and tissue veil.',
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'Custom'],
    colors: [{ name: 'Imperial Plum', hex: '#582233' }],
    stock: 5,
    fabric: 'Silk Velvet, Crushed Georgette & Tissue Dupatta',
    tags: ['Sharara', 'Velvet', 'Wedding', 'Winter Bridal'],
    rating: 4.9,
    reviewCount: 14,
    featured: true,
    trending: false,
    newArrival: true,
  },
  {
    name: 'Golden Dust Pre-Draped Concept Cocktail Saree',
    slug: 'golden-dust-pre-draped-cocktail-saree',
    gender: 'women',
    category: 'Designer Sarees',
    subcategory: 'Concept Sarees',
    price: 42000,
    salePrice: null,
    sku: 'DT-WSR-009',
    description: 'Modern pre-stitched pleated silhouette in fluid metallic lamé, featuring an attached pleated pallu and a structured crystal-embroidered sweetheart blouse.',
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'Custom'],
    colors: [{ name: 'Liquid Champagne', hex: '#F3E5AB' }],
    stock: 7,
    fabric: 'Metallic Lamé & Crystal Embellished Lycra',
    tags: ['Saree', 'Cocktail', 'Pre-Draped', 'Reception'],
    rating: 4.8,
    reviewCount: 13,
    featured: false,
    trending: true,
    newArrival: false,
  },
  {
    name: 'Luminescent Pearl White Bridal Ball Gown',
    slug: 'luminescent-pearl-white-bridal-ball-gown',
    gender: 'women',
    category: 'Gowns',
    subcategory: 'Bridal Gowns',
    price: 110000,
    salePrice: 98000,
    sku: 'DT-WGW-010',
    description: 'Cathedral-length luxury white bridal gown featuring illusion lace sleeves, sheer back with satin covered buttons, and thousands of luminous micro-pearls hand-embroidered over soft Chantilly lace.',
    images: [
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'Custom'],
    colors: [{ name: 'Pure Pearl White', hex: '#FAFAFA' }],
    stock: 2,
    fabric: 'Chantilly Lace, Silk Organza & Micro Pearls',
    tags: ['Bridal', 'Gown', 'Wedding', 'White Gown'],
    rating: 5.0,
    reviewCount: 17,
    featured: true,
    trending: true,
    newArrival: true,
  },
];

const couponsData = [
  {
    code: 'ROYAL10',
    discountType: 'percentage',
    discountValue: 10,
    minimumOrder: 25000,
    maximumDiscount: 10000,
    expiryDate: new Date('2028-12-31'),
    usageLimit: 1000,
    status: 'active',
  },
  {
    code: 'BRIDAL5000',
    discountType: 'fixed',
    discountValue: 5000,
    minimumOrder: 50000,
    maximumDiscount: 5000,
    expiryDate: new Date('2028-12-31'),
    usageLimit: 500,
    status: 'active',
  },
  {
    code: 'WELCOME5',
    discountType: 'percentage',
    discountValue: 5,
    minimumOrder: 10000,
    maximumDiscount: 3000,
    expiryDate: new Date('2028-12-31'),
    usageLimit: 2000,
    status: 'active',
  },
];

export const runSeed = async () => {
  try {
    console.log('[Seed] Connecting to database...');
    await connectDB();

    console.log('[Seed] Clearing existing collections...');
    await Promise.all([
      User.deleteMany({}),
      Product.deleteMany({}),
      Category.deleteMany({}),
      Coupon.deleteMany({}),
      Review.deleteMany({}),
    ]);

    // 1. Seed Admin & Demo Customer
    console.log('[Seed] Creating demo accounts...');
    const adminEmail = process.env.ADMIN_EMAIL || 'admin@dazzlingthread.com';
    const adminPassword = process.env.ADMIN_PASSWORD || 'Admin@12345';
    const adminName = process.env.ADMIN_NAME || 'Royal Administrator';

    const adminUser = await User.create({
      name: adminName,
      email: adminEmail,
      password: adminPassword,
      phone: '+91 98765 43210',
      role: 'admin',
      addresses: [
        {
          fullName: adminName,
          phone: '+91 98765 43210',
          street: '42, Dulha Dulhan House, Heritage Boulevard',
          city: 'New Delhi',
          state: 'Delhi',
          postalCode: '110001',
          country: 'India',
          isDefault: true,
        },
      ],
    });

    const demoCustomer = await User.create({
      name: 'Princess Ananya Singhania',
      email: 'customer@dazzlingthread.com',
      password: 'Customer@12345',
      phone: '+91 91234 56789',
      role: 'customer',
      addresses: [
        {
          fullName: 'Ananya Singhania',
          phone: '+91 91234 56789',
          street: 'Villa 14, Royal Palm Enclave, Golf Links',
          city: 'New Delhi',
          state: 'Delhi',
          postalCode: '110003',
          country: 'India',
          isDefault: true,
        },
      ],
    });

    console.log(`[Seed] Admin created: ${adminEmail}`);
    console.log(`[Seed] Demo Customer created: customer@dazzlingthread.com`);

    // 2. Seed Categories
    console.log('[Seed] Seeding categories...');
    const createdCategories = await Category.insertMany(categoriesData);
    console.log(`[Seed] Inserted ${createdCategories.length} categories.`);

    // 3. Seed Products
    console.log('[Seed] Seeding luxury bridal and groom products...');
    const createdProducts = await Product.insertMany(productsData);
    console.log(`[Seed] Inserted ${createdProducts.length} luxury products.`);

    // 4. Seed Coupons
    console.log('[Seed] Seeding discount vouchers...');
    await Coupon.insertMany(couponsData);
    console.log(`[Seed] Inserted ${couponsData.length} coupons.`);

    // 5. Seed Reviews for first few products
    console.log('[Seed] Seeding authentic verified customer reviews...');
    const sampleReviews = [
      {
        user: demoCustomer._id,
        product: createdProducts[0]._id,
        userName: 'Princess Ananya Singhania',
        rating: 5,
        title: 'Breathtaking embroidery and royal drape',
        comment: 'The craftsmanship on this sherwani is genuinely museum-grade. The zardozi work caught every light at our palace wedding.',
        verifiedPurchase: true,
        status: 'approved',
      },
      {
        user: demoCustomer._id,
        product: createdProducts[10]._id,
        userName: 'Princess Ananya Singhania',
        rating: 5,
        title: 'Dream bridal lehenga for my wedding day',
        comment: 'The Empress Noor lehenga felt surreal to wear. The weight of the silk velvet and the hand-embroidered kalis were completely breathtaking.',
        verifiedPurchase: true,
        status: 'approved',
      },
    ];
    await Review.insertMany(sampleReviews);
    console.log(`[Seed] Inserted ${sampleReviews.length} customer reviews.`);

    console.log('[Seed] Database initialization complete!');
  } catch (error) {
    console.error('[Seed Error]:', error);
  }
};

// If run directly via node seed/seed.js
if (process.argv[1]?.endsWith('seed.js')) {
  runSeed().then(async () => {
    await disconnectDB();
    process.exit(0);
  });
}
